services:
  notificator:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: notificator

    restart: "no"

    env_file:
      - .env

    networks:
      - backend

networks:
  backend:
    external: true
